version: '3.8'

services:

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    restart: always

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  test:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: [ "sh", "-c", "PYTHONPATH=/app pytest tests/ ; python -m src.database" ]
