services:
  db:
    image: postgres:13
    container_name: bookcrossing_db
    environment:
      POSTGRES_DB: bookcrossing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: bookcrossing_app
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/bookcrossing
      SECRET_KEY: your-production-secret-key-change-this
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bookcrossing_frontend
    ports:
      - "3000:3000"
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
